export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_CREATURE_FAILURE = 'GET_CREATURE_FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const GET_CREATURE_REQUEST = 'GET_CREATURE_REQUEST';
export const GET_CREATURE_SUCCESS = 'GET_CREATURE_SUCCESS';